# -*- coding: utf-8 -*-
"""Cópia de Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iKb53tnDx_1fO8exfY16YPE_pccyjKXZ
"""

# Passo 4: Importar a biblioteca Matplotlib para os gráficos
# A primeira linha garante que a biblioteca está instalada no ambiente do Colab.
!pip install matplotlib -q
import matplotlib.pyplot as plt

# Passo 1: Definir a classe Livro
# Uma classe é como um "molde" para criar objetos.
# Aqui, nosso molde "Livro" terá as características (atributos) de um livro.
class Livro:
    def __init__(self, titulo, autor, genero, quantidade):
        self.titulo = titulo
        self.autor = autor
        self.genero = genero
        self.quantidade = quantidade

# Passo 2: Criar a lista de livros (nossa biblioteca)
# Começamos com uma lista vazia que vai armazenar todos os livros cadastrados. [cite: 29]
biblioteca = []

# Passo 3: Implementar funções para gerenciar os livros [cite: 30]

# Função para cadastrar um novo livro [cite: 31]
def cadastrar_livro():
    print("\n--- Cadastro de Novo Livro ---")
    titulo = input("Digite o título do livro: ")
    autor = input("Digite o autor do livro: ")
    genero = input("Digite o gênero do livro: ")
    # Usamos try-except para garantir que a quantidade seja um número
    try:
        quantidade = int(input("Digite a quantidade disponível: "))
    except ValueError:
        print("Erro: A quantidade deve ser um número inteiro. Tente novamente.")
        return # Encerra a função se o valor não for um número

    # Cria um novo "objeto" Livro com as informações digitadas
    novo_livro = Livro(titulo, autor, genero, quantidade)
    # Adiciona o livro criado à nossa lista 'biblioteca'
    biblioteca.append(novo_livro)
    print(f"Livro '{titulo}' cadastrado com sucesso!")

# Função para listar todos os livros cadastrados [cite: 32]
def listar_livros():
    print("\n--- Lista de Livros Disponíveis ---")
    # Verifica se a lista está vazia
    if not biblioteca:
        print("Nenhum livro cadastrado na biblioteca.")
    else:
        # Percorre cada livro na biblioteca e imprime seus detalhes
        for livro in biblioteca:
            print(f"Título: {livro.titulo}, Autor: {livro.autor}, Gênero: {livro.genero}, Quantidade: {livro.quantidade}")

# Função para buscar um livro pelo título [cite: 34]
def buscar_livro():
    print("\n--- Busca de Livro por Título ---")
    titulo_busca = input("Digite o título do livro que deseja buscar: ")
    livro_encontrado = None

    # Percorre a biblioteca para encontrar o livro
    for livro in biblioteca:
        # Compara os títulos em minúsculas para não diferenciar maiúsculas/minúsculas
        if livro.titulo.lower() == titulo_busca.lower():
            livro_encontrado = livro
            break # Para a busca assim que encontra o primeiro resultado

    if livro_encontrado:
        print("\n--- Livro Encontrado ---")
        print(f"Título: {livro_encontrado.titulo}, Autor: {livro_encontrado.autor}, Gênero: {livro_encontrado.genero}, Quantidade: {livro_encontrado.quantidade}")
    else:
        print(f"O livro com o título '{titulo_busca}' não foi encontrado.")

# Passo 4: Função para gerar o gráfico de livros por gênero
def gerar_grafico_generos():
    print("\n--- Gerando Gráfico de Livros por Gênero ---")
    if not biblioteca:
        print("Não há livros cadastrados para gerar um gráfico.")
        return

    # Dicionário para contar quantos livros de cada gênero existem
    contagem_generos = {}
    for livro in biblioteca:
        # Se o gênero já foi contado antes, soma mais um
        if livro.genero in contagem_generos:
            contagem_generos[livro.genero] += 1
        # Se for um gênero novo, adiciona ao contador com o valor 1
        else:
            contagem_generos[livro.genero] = 1

    # Prepara os dados para o gráfico
    generos = list(contagem_generos.keys())
    quantidades = list(contagem_generos.values())

    # Cria o gráfico de barras
    plt.figure(figsize=(10, 6)) # Define o tamanho da figura do gráfico
    plt.bar(generos, quantidades, color='skyblue')
    plt.title('Quantidade de Livros por Gênero')
    plt.xlabel('Gênero')
    plt.ylabel('Quantidade de Livros')
    plt.show() # Exibe o gráfico

# Passo 5: Testar o sistema (Menu principal) [cite: 37]
# Loop para manter o programa rodando até o usuário decidir sair
def menu_principal():
    while True:
        print("\n--- Sistema de Gerenciamento da Biblioteca ---")
        print("1. Cadastrar Novo Livro")
        print("2. Listar Todos os Livros")
        print("3. Buscar Livro por Título")
        print("4. Gerar Gráfico por Gênero")
        print("5. Sair")

        opcao = input("Escolha uma opção: ")

        if opcao == '1':
            cadastrar_livro()
        elif opcao == '2':
            listar_livros()
        elif opcao == '3':
            buscar_livro()
        elif opcao == '4':
            gerar_grafico_generos()
        elif opcao == '5':
            print("Saindo do sistema. Até logo!")
            break
        else:
            print("Opção inválida. Por favor, tente novamente.")

# Inicia o programa chamando o menu principal
menu_principal()